[package]
name = "exrpc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
discord-rich-presence = "0.2.4"
emf-rs = { git = "https://codeberg.org/ExanimaModding/Toolkit.git", branch = "plugins", version = "0.1.0-beta.1" }
log = "0.4.22"
pretty_env_logger = "0.5.0"
