[plugin]
id = "com.sunglasses.exrpc"
name = "exrpc"
description = """
Custom Discord RPC implementation for Exanima
"""
version = "1.0.0"
supported_versions = ["1.0.0"]
url = "https://github.com/sunglasseslol/exrpc"
executable = "exrpc.dll"
enabled = true

[plugin.author]
name = "Sunglasses"
contact = "sunglasses."
url = "https://github.com/sunglasseslol/exrpc"

[[setting]]
name = "Activity/Status"
id = "exrpc_activity"
description = "Set the activity/status on your profile"
default = "Running around..."

[[setting]]
name = "Details"
id = "exrpc_details"
description = "Set the details on your profile"
default = "morning @Jango"

[[setting]]
name = "Icon"
id = "exrpc_icon"
description = "Sets the icon on your profile. Possible icons: exanima, hellmode, modded"
default = "exanima"

