[plugin]
id = "com.sunglasses.exrpc"
name = "exrpc"
description = """
Custom Discord RPC implementation for Exanima

Credits: 
thanks to the emtk friends for helping me out a bunch (rie and dea) <3

source code can be found by pressing that button somwhere where it says source
its also at https://github.com/sunglasseslol/exrpc
check out the readme.md in the github for some important info too

Unofficial Modding Discord: https://discord.gg/pfZdW9AUbM
EMTK Discord: https://discord.gg/6bbzGgsNs
Exanitype: https://github.com/YewYew/Exanitype
"""
version = "1.0.0"
supported_versions = ["1.0.0"]
url = "https://github.com/sunglasseslol/exrpc"
executable = "exrpc.dll"
enabled = false

[plugin.author]
name = "Sunglasses"
url = "https://github.com/sunglasseslol/exrpc"

[[setting]]
name = "Details/Status"
id = "exrpc_details"
description = "Set the details/status on your profile"
default = "Running around..."

[[setting]]
name = "Icon"
id = "exrpc_icon"
description = "Sets the icon on your profile. Possible icons: exanima, hellmode, modded"
default = "exanima"

[[setting]]
name = "State"
id = "exrpc_state"
description = "Sets the state on your profile."
default = "Only works if checkbox below is enabled"

[[setting]]
name = "Enable State"
id = "exrpc_stateenabled"
description = "Enables the state to show on your profile"
default = false